#!/bin/bash
chbr () {
    if [ "$1" -gt 500 ]; then
        echo "Brightness higher than 500 is not allowed"
        exit 1
    fi
    if [ "$1" -lt 25 ]; then
        echo "Brightness lower than 25 is not allowed"
        exit 1
    fi
    echo "$1" | sudo tee /sys/class/backlight/apple-panel-bl/brightness
}
