#!/bin/bash
DAILY_PATH=~/Documents/Notes/daily

taskfile_build () {
    export TASKS_OUTPUT="/tmp/$(date +%F).taskfile"
    ~/Tools/Tasks/task_bin list >| $TASKS_OUTPUT
}

tasks () {
    taskfile_build
    nvim --cmd "cd ~/Documents/Notes" +" 2 " $TASKS_OUTPUT
}
