#!/bin/bash
export DAILY_PATH=~/Notes/daily

make_daily () {
    DAILY_FILE="$DAILY_PATH/$(date +%F).md"
    cp -v ~/Notes/templates/daily.md "$DAILY_FILE"
    sed -i 's/{{date:dddd, DD MMMM YYYY}}/'"$(date +"%A, %d %B %Y")"'/g' "$DAILY_FILE"
}
