#!/bin/bash
DAILY_PATH=~/Notes/daily

note () {
    [[ ! -f $DAILY_PATH/$(date +%F).md ]] && cp -v ~/Notes/templates/daily.md $DAILY_PATH
    echo "$@" >> $DAILY_PATH/$(date +%F).md
}

notes () {
    [[ ! -f $DAILY_PATH/$(date +%F).md ]] && cp -v ~/Notes/templates/daily.md $DAILY_PATH
    nvim +"cd ~/Notes | normal Gzz" ~/Notes/daily/$(date +%F).md
}

